name: Auto Merge Pull Request

on:
  push:
    branches:
      - dev

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get last commit message
        id: commit_message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "::set-output name=message::$COMMIT_MSG"
      - name: Create or Update Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh_pr_up() {
            local title="$1"
            local body="$2"
            gh pr create --base main --head dev --title "$title" --body "$body" || \
            gh pr edit --base main --head dev --title "$title" --body "$body"
          }
          COMMIT_MSG=$(echo "${{ steps.commit_message.outputs.message }}")
          gh_pr_up "$COMMIT_MSG" "Description"
