name: Create PR from Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto-merge dev into main
          branch: dev
          base: main
          title: Auto-merge dev into main
          body: Auto-merge dev into main
